# Default colors
[colors.primary]
background = '#161616'
foreground = '#dde1e6'

# Normal colors
[colors.normal]
black   = '#262626'
red     = '#ee5396'
green   = '#42be65'
yellow  = '#ffe978'
blue    = '#33b1ff'
magenta = '#ff7eb6'
cyan    = '#3ddbd9'
white   = '#dde1e6'

# Bright colors
[colors.bright]
black   = '#393939'
red     = '#ee5396'
green   = '#42be65'
yellow  = '#ffe978'
blue    = '#33b1ff'
magenta = '#ff7eb6'
cyan    = '#3ddbd9'
white   = '#f2f4f6'
