add_newline = false
format = "$directory$fill$git_branch$git_status$cmd_duration$line_break$character"
fill.symbol = " "

[character]
success_symbol = "[](#7ba5dd)"
error_symbol = "[](#ee6a70)"
vicmd_symbol = "[](#ffb29b)"

[directory]
format = "[]($style)[  ](bg:#101415 fg:#7ba5dd)[$path](bg:#101415 fg:#c5c8c9 bold)[ ]($style)"
style = "bg:none fg:#101415"
truncation_length = 3
truncate_to_repo = false

[git_branch]
format = "[]($style)[[  ](bg:#101415 fg:#6fadea bold)$branch](bg:#101415 fg:#c5c8c9)[ ]($style)"
style = "bg:none fg:#101415"

[git_status]
format = "[]($style)[$all_status$ahead_behind](bg:#101415 fg:#c5c8c9 bold)[ ]($style)"
style = "bg:none fg:#101415"
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count} "
diverged = "↑${ahead_count} ⇣${behind_count} "
up_to_date = " "
untracked = "?${count} "
stashed = " "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = " ${count} "

[cmd_duration]
min_time = 1
format = "[]($style)[[  ](bg:#101415 fg:#7ba5dd bold)$duration](bg:#101415 fg:#c5c8c9 bold)[]($style)"
disabled = false
style = "bg:none fg:#101415"

#command_timeout = 1000 
