add_newline = false
format = "$directory$git_branch$git_status$cmd_duration\n[󰘧](fg:cyan) "
git_branch.format = "via [$symbol$branch(:$remote_branch)]($style) "
command_timeout = 1000

[directory]
format = "[$path](bg:none fg:blue) "

[git_status]
conflicted = "="
ahead = "⇡ ${count}"
behind = "⇣ ${count}"
diverged = "↑ ${ahead_count} ⇣ ${behind_count} "
up_to_date = " "
untracked = "?${count}"
stashed = "󰏖 "
modified = "!${count}"
staged = "+${count}"
renamed = "» ${count}"
deleted = " ${count}"
